### ISSUE TITLE
Hardcoded localhost

### ISSUE THREAD

**Issue by shauntrennery** [RafalWilinski/express-status-monitor#1]
The socket.io connection is hardcoded to localhost:

https://github.com/RafalWilinski/express-status-monitor/blob/master/index.html#L139

**Comment by RafalWilinski** [comment]
Good catch, thanks! I'll fix that asap

**Comment by RafalWilinski** [comment]
Fixed: https://github.com/RafalWilinski/express-status-monitor/commit/13b7e9ce841738b91d39069a1c99680138754d75

However, it leads me to another concern, hardcoded port. I would like to minimize dependencies and not use any templating engine for that. Any suggestions?

**Comment by shauntrennery** [comment]
I agree with your minimal dependency approach. I would fs.readFileSync the html file and then replace {{PORT}}, {{TITLE}} tokens using a simple handlebars like regex: http://stackoverflow.com/a/17304898

**Comment by RafalWilinski** [comment]
Thanks. I've just added this, seems to be working fine: https://github.com/RafalWilinski/express-status-monitor/commit/d30faec1362bb55d20a07922c03fa6a3e6cb0d3c
