### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by PierreBresson** [RafalWilinski/express-status-monitor#11]
Hi,

I did like requested, I put the code just after init of express :

```
var app = express();

app.use(require('express-status-monitor')());
```

And I get no data when I go to /status: 

![capture d ecran 2016-08-18 a 09 42 49](https://cloud.githubusercontent.com/assets/8709134/17766094/a62c63c6-6529-11e6-83cd-a06f808a9ad3.png)

Any idea how to fix that? (my host is heroku)

**Comment by RafalWilinski** [comment]
We had some problems with Heroku with previous versions (pre 0.0.9). Version 0.0.9 fixes that because it adds HTTPS support (including Heroku). 

Proof: https://safe-fjord-78017.herokuapp.com/status

**Comment by PierreBresson** [comment]
Update to 0.0.9 and it's working.

Thanks ;)
