### ISSUE TITLE
Demo application is not working

### ISSUE THREAD

**Issue by ivanvs** [RafalWilinski/express-status-monitor#111]
If someone tries to open demo application it will find out that application is not there. So on this [link](https://express-status-monitor-example-fjovaypblp.now.sh/) that can be found on library front page, there is no demo. 

Could someone check what is happening with demo application?

**Comment by RafalWilinski** [comment]
Probably it was removed because was hosted for free... Gonna look into it soon. Thanks for reporting issue.

**Comment by codepupper** [comment]
Since this is still open and I wanted to check it out as well, how about hosting it on Netlify? I only heard good things about them

**Comment by YasharF** [comment]
If anyone is interested to see a demo, you can check it out as part of the demo for [hackathon-starter](https://github.com/sahat/hackathon-starter), we use express-status-monitor in there.  For now, Walcony is planning to continue hosting that demo instance.
