### ISSUE TITLE
provide custom page title

### ISSUE THREAD

**Issue by lekhnath** [RafalWilinski/express-status-monitor#13]
Can I change the default 'Express Status' page title?

**Comment by RafalWilinski** [comment]
Not yet, I'll consider that.

**Comment by ecwyne** [comment]
:+1: 
I was considering making a PR adding an `appName` property to the config. The title and page header would say `${appName} status`

**Comment by AussieFlem** [comment]
+1 for me on this one. Put it in as #23 before I found this one.

**Comment by lekhnath** [comment]
Instead of `${appName} status` I prefer `${title}` so that nothing is hard coded @ecwyne

**Comment by RafalWilinski** [comment]
Added: https://github.com/RafalWilinski/express-status-monitor/commit/24a8bd3513d6a1b165ad3b38d1068769a2b58f1f

**Comment by lekhnath** [comment]
Published in npm ?

**Comment by lekhnath** [comment]
Works when installed from github `npm i RafalWilinski/express-status-monitor#master` for now. Please publish to npm too.

**Comment by RafalWilinski** [comment]
`0.0.10` just landed on npm

**Comment by vgoklani** [comment]
@RafalWilinski I have to say, watching this project grow so quickly from 100 stars to 1300 is really really amazing! Congratulations :)
