### ISSUE TITLE
Socket.io not working

### ISSUE THREAD

**Issue by abacaj** [RafalWilinski/express-status-monitor#14]
Followed instructions getting this error with default settings:

![err](https://cloud.githubusercontent.com/assets/7272343/17776373/4246e1b4-652a-11e6-85b3-b977b974a6da.JPG)

Running on:
Ubuntu 14.04.4 with node v6.2.2

**Comment by RafalWilinski** [comment]
Might be silly but refresh the page and everything will be alright :D

**Comment by abacaj** [comment]
Different error now:

![not-working](https://cloud.githubusercontent.com/assets/7272343/17776507/eafb791e-652a-11e6-8b62-3b57914b55a4.JPG)

**Comment by afollestad** [comment]
I'm getting the same error pretty frequently, it's on an HTTPS server btw

**Comment by jc21** [comment]
Yep definitely HTTPS related, using HTTP works for me instead of HTTPS. Chrome gives the ERR_DISALLOWED_URL_SCHEME error.

**Comment by AussieFlem** [comment]
That's a very similar error what I'm seeing in #27 (FWIW)

**Comment by jabis** [comment]
@afollestad are you using a real cert, or self-signed one? At least some node versions will cease to co-operate without a valid one. You can - but shouldn't - use certain env-vars in your app (on the top of my hat `process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0'; `, should do it for self-signed certificates, which I usually use on development environments ( so btdt in another context; )

**Comment by afollestad** [comment]
@jabis a real cert

**Comment by jabis** [comment]
@RafalWilinski I believe this are two distinct errors, as the OP is having 404 not found, while @afollestad is having a handshake error, would be wise to split maybe.
@afollestad next I'd like to point out that if you're not reverse proxying the /socket.io yours could very well be cross-origin problem. Are you just deploying the example as it is, or are you trying to integrate it with some other existing software (maybe using another socket.io already)?

**Comment by afollestad** [comment]
I'm not doing anything special. It's all contained on my remote Node.js application, running on an Ubuntu server. It should work as is.

**Comment by jabis** [comment]
@afollestad if you access www.remote.tld and you access the serverside component from www.remote.tld:4000 then that is considered cross-origin, at least on modern chrome and firefox browsers :) If you on the other hand are reverse proxying the /socket.io port to "upstream" aka node process, then it should not be, and depending on your httpd, and node version, could be a proxy option or header problem - https( read: wss for sockets ) is really touchy with cross-origin, scripting.
