### ISSUE TITLE
eventloop vs node-alpine

### ISSUE THREAD

**Issue by paulodfreitas** [RafalWilinski/express-status-monitor#143]
Hi,

First thank you. This package is a great work.

The new version add dependency of event-loop, that depend of node-gyp, and required a Python executable to properly install. This addition is a problem for users, like me, who are deploying our applications using node _alpine_ Docker images, because this images doesn't come with Python to be as light as possible.

Is possible to make the new version (1.3.0) a BC version (so 2.0), or implement it in a manner that event-loop dependency is a required-package?

**Comment by RafalWilinski** [comment]
Thanks for this bug report @paulodfreitas! I wasn't aware of that. Going to address this problem asap

**Comment by paulodfreitas** [comment]
👍

**Comment by Naxos84** [comment]
This still seems to be an issue?
Is there any progress?
What version is needed to be able to have the python error removed?

**Comment by paulodfreitas** [comment]
Version 1.3.3 should work fine without python.
