### ISSUE TITLE
ERR_CONNECTION_REFUSED error on DigitalOcean

### ISSUE THREAD

**Issue by ycczkl** [RafalWilinski/express-status-monitor#18]
I got this error in console `http://XXX.XXX.XXX.XXX:41338/socket.io/?EIO=3&transport=polling&t=LQUqd9f net::ERR_CONNECTION_REFUSED`. Any idea about this error?

**Comment by ecwyne** [comment]
@ycczkl what version of the package are you using? The most up to date version uses the same port as your application (not 41338)

**Comment by ycczkl** [comment]
This problem has been solved after I upgrade the package to v0.09. Thanks! Will close this issue
