### ISSUE TITLE
Don't extend native prototypes

### ISSUE THREAD

**Issue by forivall** [RafalWilinski/express-status-monitor#19]
https://github.com/RafalWilinski/express-status-monitor/blob/d6327597a75b08ca923ce9ff444ca0647842285a/index.js#L25

Don't.

**Comment by RafalWilinski** [comment]
Good point, I'd rather write a private function for that or something, thanks.

**Comment by RafalWilinski** [comment]
https://github.com/RafalWilinski/express-status-monitor/commit/beb988f1518e78c90494cedf42f71caf13b3e7f7 Merged & fixed.
