### ISSUE TITLE
unneeded comparison

### ISSUE THREAD

**Issue by gloomybrain** [RafalWilinski/express-status-monitor#2]
This kind of comparison `config === {}` ([here](https://github.com/RafalWilinski/express-status-monitor/blob/054cc976ac40285d2c4f1e557cedfda8857eb0b5/index.js#L66)) will always return `false` because `{}` here is a new object literal.

**Comment by RafalWilinski** [comment]
True, I forgot about that. Let me fix that.

**Comment by RafalWilinski** [comment]
Fixed: https://github.com/RafalWilinski/express-status-monitor/commit/af7c56fbdaf37b69c47ca470b0aabe88be2083b1
