### ISSUE TITLE
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by kitavidavis** [RafalWilinski/express-status-monitor#211]
The default configuration seems to work fine in localhost.
However, running it in a production environment results to error 400. 
Any means on how to solve this?

**Comment by m-echaves** [comment]
@kitavidavis Same for me. It is deployed in a AWS EC2 Cluster but I am getting this issue. Localhost works fine.

**Comment by kitavidavis** [comment]
@pml-eduardochaves the issue was due to proxy configurations. Check your header's Content-Security-Policy configuration as well. If you are running another instance of socket connection, you might also consider looking at how it is affecting your express-status-monitor WebSocket connection.
