### ISSUE TITLE
Unnecessary IIFE in index.js

### ISSUE THREAD

**Issue by Hurtak** [RafalWilinski/express-status-monitor#28]
Why index.js is wrapped in IIFE? As far as I know this is only useful in front-end world if you are not using any module bundler and are worriend about other libraries using global variables with same name.

**Comment by Hurtak** [comment]
On the other hand, in front-end code in index.html where IIFE could be useful, it is not used.

**Comment by RafalWilinski** [comment]
Good point, I'll fix that asap.
