### ISSUE TITLE
Error: Cannot find module 'on-headers'

### ISSUE THREAD

**Issue by moongift** [RafalWilinski/express-status-monitor#33]
When I try an example, I got an error message that "Error: Cannot find module 'on-headers'". I resolved it execute "npm install" on parent directory.

1. clone repository  
`git clone https://github.com/RafalWilinski/express-status-monitor.git`
2. change directory  
`cd express-status-monitor`
3. execute command  
`npm install`
4. change directory  
`cd examples`
5. execute command again  
`npm install`
6. start server  
`node index.js`

That's all. You should update README document for your cool software.

Great Job!

**Comment by RafalWilinski** [comment]
I don't think we should teach people "How to Node.js" in this repository. These instructions are universal for every module, let's keep it minimalistic for now.
