### ISSUE TITLE
Do not use sync IO methods

### ISSUE THREAD

**Issue by Hurtak** [RafalWilinski/express-status-monitor#34]
In

https://github.com/RafalWilinski/express-status-monitor/blob/master/index.js#L99-L100

```js
      .replace(/{{script}}/g, fs.readFileSync(path.join(__dirname, '/app.js')))
      .replace(/{{style}}/g, fs.readFileSync(path.join(__dirname, '/style.css')));
```

You are using sync methods, this seems like a bad idea. As far as I know, sync methods will block the whole thread, while doing the IO. If you use async method, that thread will be free to handle other requests until feadFile is finished.

**Comment by RafalWilinski** [comment]
it's happening only once, when server starts and takes less than couple of
ms to handle. I don't think it's an issue.
