### ISSUE TITLE
ready file to read file sync

### ISSUE THREAD

**Issue by mattiaerre** [RafalWilinski/express-status-monitor#39]
Hi @RafalWilinski I was trying to add some tests to the middleware and I just noticed that the routine that reads the html file containing the template is asynchronous; I think it should be synchronous and I believe it will also fix some initial loading problems (sometimes you don't see any info in the console)

I am referring in particular to:

https://github.com/RafalWilinski/express-status-monitor/blob/master/index.js#L79-L85

```js
  let renderedHtml;
  fs.readFile(path.join(__dirname, '/index.html'), function (err, html) {
    renderedHtml = html.toString()
      .replace(/{{title}}/g, config.title)
      .replace(/{{script}}/g, fs.readFileSync(path.join(__dirname, '/app.js')))
      .replace(/{{style}}/g, fs.readFileSync(path.join(__dirname, '/style.css')));
  });
```
the code should be changed into:

```js
  let renderedHtml =
    fs.readFileSync(path.join(__dirname, '/index.html'))
      .toString()
      .replace(/{{title}}/g, config.title)
      .replace(/{{script}}/g, fs.readFileSync(path.join(__dirname, '/app.js')))
      .replace(/{{style}}/g, fs.readFileSync(path.join(__dirname, '/style.css')));
```

if you think this is a good idea I will start raising a PR w/ tests containing also this bit; you can review it and merge it then we can incrementally add more tests

**Comment by RafalWilinski** [comment]
Cool, thanks for handling it!

**Comment by RafalWilinski** [comment]
Thanks for fixing @mattiaerre! btw I've added you to `contributors` section, I hope you like it :octocat:

**Comment by mattiaerre** [comment]
hi @RafalWilinski of course I do; thank you very much!
