### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cpu' of undefined

### ISSUE THREAD

**Issue by bonesoul** [RafalWilinski/express-status-monitor#47]
version: 0.1.2

**Comment by mattiaerre** [comment]
hi @bonesoul this happens the very 1st time you access the /status endpoint correct? then you refresh the page and it looks fine, right? are you able to add more details to this issue? thanks,

**Comment by bonesoul** [comment]
yes exactly like you explained. gets fixed after a few more reloads.

working on node 6.5

**Comment by mattiaerre** [comment]
this issue will be fixed by #48 

// cc @RafalWilinski
