### ISSUE TITLE
Does not work with nodemon

### ISSUE THREAD

**Issue by mitrick2** [RafalWilinski/express-status-monitor#5]
While running my express app with nodemon version 3.7.3, I did receive the following error:

stat.memory = stat.memory / 1024 / 1024;
TypeError: Cannot read property 'memory' of null

It then ends the nodemon process.

Great package - thank you!

**Comment by RafalWilinski** [comment]
Thanks, I'll try to reproduce that error and fix that asap.

**Comment by TravelingTechGuy** [comment]
@mitrick2 Nodemon is currently at version 1.10.0. Just tested my app and the status is showing well on Nodemon, and does not cause any crash.

PS: did you specify your NPM version by any chance?

**Comment by mitrick2** [comment]
@TravelingTechGuy  I was on version 1.9.0 of Nodemon.  Updated it and haven't been able to reproduce either on 1.10.0.  FWIW:  Windows 10.  Closing, and thanks for the fast response!

**Comment by RafalWilinski** [comment]
`pidusage` module could act strange on W10. Same goes with `os.loadavg`
