### ISSUE TITLE
A fork: trek-status-monitor

### ISSUE THREAD

**Issue by fundon** [RafalWilinski/express-status-monitor#51]
https://github.com/trekjs/status-monitor

**Comment by RafalWilinski** [comment]
?

**Comment by fundon** [comment]
Just Likes koa-monitor.

**Comment by Hurtak** [comment]
Wouldn't it be better if there was some common core and express/koa/trek support was handled with some thin wrapper instead of forking the whole repository? Or are these frameworks too different?

**Comment by fundon** [comment]
Express uses `callback-style` for composing middleware and has three params `(req, res, next) => { next() }`
Koa or Trek returns a Promise and has two params `(ctx, next) => { return next() }`.

**Comment by Hurtak** [comment]
Ok, but still the frontend and lots of backend helper functions from could be shared between the implementations
