### ISSUE TITLE
Host a demo app on AWS spot instance

### ISSUE THREAD

**Issue by RafalWilinski** [RafalWilinski/express-status-monitor#53]
Just like title says. Give everyone opportunity to see tool in action without downloading & installing it. Use AWS Spot (probably with spotinst?) because it's one of the most cheapest solutions, it also could integrate very nicely with CodeDeploy + github webhooks etc. Heroku is not an option because it goes down every X minutes.

**Comment by mattiaerre** [comment]
I like the idea 👍 
Heroku Hobby is $7 dyno/month not sure about AWS Spot although.
It could be also used as a playground when a new release has been deployed.
Thanks,

**Comment by johnbrett** [comment]
https://zeit.co/now is another solution, free for open source :)

**Comment by RafalWilinski** [comment]
Thanks @johnbrett! Brilliant solution, seamless integration, fast and free!

**Comment by mattiaerre** [comment]
this is really interesting!
thank you very much for sharing @johnbrett

**Comment by johnbrett** [comment]
No worries, I think what Zeit are doing is pretty awesome, and supporting open source too so happy to promote them!

**Comment by mattiaerre** [comment]
@johnbrett sweet, do you know if it is possible to implement CI w/ GitHub webhook and Travis CI for instance?

**Comment by johnbrett** [comment]
I imagine its possible, but the only experience I have it with it is hosting some demo apps with zeit. They've a slack where I'm sure you could ask, if you get that work flow working I'd be VERY interested in reading about it though 😉

**Comment by mattiaerre** [comment]
FYI I asked them on Slack if the following scenario is supported:

"w/ heroku every time you push to GitHub you can also publish on heroku (if CI passes for instance) is this a possible scenario w/ "now"?"

answer:

"not yet, but it's on our issue list (on the private roadmap)"

// cc @johnbrett @RafalWilinski

**Comment by RafalWilinski** [comment]
Thanks @mattiaerre for this research! I'll try to implement that in the next few days.
