### ISSUE TITLE
Add an ability to disable selected charts

### ISSUE THREAD

**Issue by RafalWilinski** [RafalWilinski/express-status-monitor#57]
Just like title says, add optional parameter to options which hides selected charts

**Comment by mattiaerre** [comment]
@RafalWilinski what about enhancing the UI w/ collapsable sections instead?

**Comment by RafalWilinski** [comment]
I think disabling them in configuration might be better because:
- you have persistency, you don't have to collapse selected charts every time you visit page
- adding collapsibility might require some additional dependencies which I'm not a big fan of
- you might just keep some metrics secret as an admin for developers

**Comment by mattiaerre** [comment]
hi @RafalWilinski you are right, still, you can have persistence using the localStorage for instance. but of course, this was only another idea. I'll be happy to help you w/ this issue btw; just let me know.

**Comment by rpunkfu** [comment]
Sorry @RafalWilinski is on vacation
