### ISSUE TITLE
Security Vulnerability in serveral package dependencies WS, Negotiator

### ISSUE THREAD

**Issue by idanielsteven** [RafalWilinski/express-status-monitor#58]
NSP found these packages need to be moved from/to to fix security vulnerabilties

**WS from 1.1.0 to 1.1.1 (patch fix)**
_Module ws has a known vulnerability: "DoS due to excessively large websocket message"_

**Negotiator from 0.4.9 to 0.6.1 (patch fix) ISSUE:** 
_Module negotiator has a known vulnerability: "Regular Expression Denial of Service"_

**Comment by RafalWilinski** [comment]
I feel like it's not actionable for now, it's socket.io issue. I've added Snyk to watch these vulnerabilities regularly.

**Comment by idanielsteven** [comment]
I think its very actionable, its simply a matter of upating to the patched versions of these two dependencies whichi i provided. A security issue on a dependency is a security issue on this project. IMO.

Regards.

**Comment by idanielsteven** [comment]
I opened an issue on Socket.IO's git/issues. I'll keep you apprised of a potential fix/release.

**Comment by RafalWilinski** [comment]
This should resolve the problem: https://github.com/RafalWilinski/express-status-monitor/pull/62/files
