### ISSUE TITLE
Requests per second sometimes show as NaN or Infinity

### ISSUE THREAD

**Issue by miparnisari** [RafalWilinski/express-status-monitor#6]
As the title says really. If there's any info that I can provide to make debugging easier, let me know!

**Comment by RafalWilinski** [comment]
Would be great but simple `if zero then one` should do the job.

**Comment by abacaj** [comment]
Encountered this as well - also the actual chart breaks after receiving many requests.

![bug](https://cloud.githubusercontent.com/assets/7272343/17777237/c1419858-652d-11e6-8bc0-ac0ad3cf77c2.JPG)

**Comment by idanielsteven** [comment]
Getting this too, we see this error in Chrome:

WebSocket connection to 'wss://xxx.xxxx.xxx/socket.io/?EIO=3&transport=websocket&sid=3jaeKKtPa3LdM7P4AAAI' failed: Error during WebSocket handshake: Unexpected response code: 400

and Also:

Chart.bundle.min.js:15 Uncaught TypeError: Cannot read property '_view' of undefined

**Comment by jmls** [comment]
yup, just got this.

**Comment by RafalWilinski** [comment]
Guys, how many requests do you got before crash?

**Comment by RafalWilinski** [comment]
https://github.com/RafalWilinski/express-status-monitor/pull/52

**Comment by RafalWilinski** [comment]
I think I've fixed that. I'd be glad if someone could confirm that. Version `0.1.3`

**Comment by mattiaerre** [comment]
hi @RafalWilinski same here,
I still can see NaN at the very beginning for instance in the "Requests per Second" section
thanks,

**Comment by rpunkfu** [comment]
Sorry @RafalWilinski is on vacation

**Comment by divyam3897** [comment]
hi, I see the count as always "0.00" in response time and requests per second though graph shows the requests and response time.

**Comment by ssashita** [comment]
Me too - on express-atatus-monitor 1.0.1
