### ISSUE TITLE
request/response stats don't appear to work when mounted at a path

### ISSUE THREAD

**Issue by thom-nic** [RafalWilinski/express-status-monitor#63]
I followed the readme example and mounted the monitor like:
```javascript
    router.get('/status', authenticated, require('express-status-monitor')());
```
in order to authenticate requests to the status monitor page.  However when doing so it appears request stats are no longer captured, presumably because the status monitor isn't acting as a middleware to intercept requests...
<img width="658" alt="screen shot 2016-11-14 at 11 38 27 am" src="https://cloud.githubusercontent.com/assets/95562/20274503/d4a375cc-aa62-11e6-871c-2565dda7a940.png">

Is there a way to mount the monitor middleware separate from the UI request handler?

**Comment by mattiaerre** [comment]
this is a very interesting one @thom-nic have you been able to track down the issue? I think you are right when you say it is the `onHeadersListener` that is not called anymore when there is an authentication strategy in place; I'll be more than happy to help w/ this bug. Any additional info would be good.
Thanks,

// cc @RafalWilinski

**Comment by RafalWilinski** [comment]
Does this problem persist in latest version (0.1.6)

**Comment by mattiaerre** [comment]
yes it does, I just checked w/ the new version running

// cc @RafalWilinski @thom-nic

**Comment by thom-nic** [comment]
I think I does not have to do with any auth strategy per se, just where the monitor is placed within the middleware/request routing chain.  Using`app.use(middleware)` before your routes passes all requests and that listener is able to collect request stats.  Passing `app.get('/status', middleware)` means only `GET /status` requests get sent to the middleware.  I think something similar to this would be an ideal solution...

```javascript
const {middleware, statusRoute} = require('express-status-monitor')();
app.use(middleware);
app.get('/status', authenticated, statusRoute);
```

For backward compat you could just add those properties to the existing middleware function you're exporting now.  So middleware-wrapper.js would look like....
```javascript
const middleware = (req, res, next) => { .... } // line 19 of middleware-wrapper.js
middleware.middleware = middleware;
middleware.statusRoute = (req ,res) => { res.send(renderedHtml); }
return middleware;
```

You have to worry that the status page route might not be mounted at the same point that the middleware assumes, e.g. if no config is given and then it's mounted at `app.get('/console', statusRoute)` the middleware still assumes it should respond with the HTML page for `GET /status` - maybe instruct the user to pass `{path: null}` so the condition check at line 23 will never pass.  Otherwise you'd be leaking an unauthenticated status page even though the user thought they protected it when they did `app.get('/status', authenticated, statusRoute);`

As it stands today, it looks like if you mounted at a non-default path but didn't specify that in the config it would not work anyway.  e.g. `app.get('/console', authenticated, require('express-status-monitor')());` looks like it will probably never work.

**Comment by mattiaerre** [comment]
hi @thom-nic I think that what you are pointing out here is correct. I like your suggestion; now you are right: it is working only because we are placing the `/status` path at the very top of the chain. w/o authentication the middleware is able to collect data but I assume that w/ the auth in place it is no longer working as part of the middlewares group as it is mounted w/ a `.get(` and not w/ a `.use(` as you highlighted. I think that we should add also tests around scenarios w/ different paths.

// cc @RafalWilinski

**Comment by rpunkfu** [comment]
Sorry @RafalWilinski is on vacation

**Comment by rpunkfu** [comment]
I'm the owner now

**Comment by thom-nic** [comment]
I can take a stab at this soon if core team is in alignment and nobody else is already working on it...  Pls let me know @RafalWilinski @mattiaerre

**Comment by RafalWilinski** [comment]
Sure, you can try fixing it. I bet Mattia is also ok with that.

**Comment by RafalWilinski** [comment]
Actually, It would be pretty cool!

**Comment by mattiaerre** [comment]
@thom-nic @RafalWilinski absolutely happy about this! go for it man 👍

**Comment by thom-nic** [comment]
Thx.  FYI I am going to follow this up with a PR for #66 - pls confirm if that is OK too.
