### ISSUE TITLE
Using module with socket.io in project

### ISSUE THREAD

**Issue by niallobrien** [RafalWilinski/express-status-monitor#64]
Hi, I'm trying to add socket.io support to Hackathon Starter (https://github.com/sahat/hackathon-starter/) and am running into the following issue: https://github.com/sahat/hackathon-starter/issues/621#issuecomment-261622512

The person who commented was right, disabling Express-Status-Monitor does work, but ideally I'd like to get everything working. The documentation seems a little vague, you mention setting a `port` but I don't see that config option documented. Regardless, I tried 
```
app.set('port', process.env.PORT || 3000);
...
...
...
app.use(expressStatusMonitor({ websocket: io, port: app.get('port') }));
``` 
and I still cannot get everything to work correctly. `io` is declared as so:
```
const app = express();
const server = require('http').Server(app);
const io = require('socket.io')(server);
```
Can you please advise? Thanks in advance.

**Comment by rpunkfu** [comment]
Sorry @RafalWilinski is on vacation

**Comment by rpunkfu** [comment]
I'm the owner now

**Comment by RafalWilinski** [comment]
That's weird. According to my latest changes and test his *should* work.  

Have you tried spawning `socket.io` independently from `express` instance? Like here: https://github.com/RafalWilinski/express-status-monitor/blob/master/examples/index.js#L7 (it uses just port in constructor, not whole `app`).

**Comment by niallobrien** [comment]
Hi @RafalWilinski - I'm not entirely sure how I'd adjust my setup to accommodate. Do you think you could take a look please? Thanks in advance.

https://github.com/niallobrien/hackathon-starter-plus/blob/master/app.js#L39
https://github.com/niallobrien/hackathon-starter-plus/blob/master/app.js#L130

**Comment by niallobrien** [comment]
Hey @RafalWilinski - have you had a chance to look at this? Thanks in advance.

**Comment by RafalWilinski** [comment]
@niallobrien 

Sorry for taking it so much time but I'm really busy right now. 

I've investigated this issue and here's what I came with:
```
const socketIoPort = 3001;
const app = express();
const io = require('socket.io')(socketIoPort);

app.set('port', process.env.PORT || 3000);
app.use(expressStatusMonitor({ websocket: io, port: socketIoPort }));
```

You have to create `socket.io` instance using port parameter, not `HttpServer`. Also, you cannot use the same port because of `EADDRINUSE`.

Hope that helps.
