### ISSUE TITLE
Automate publishing to npm once PR is merged

### ISSUE THREAD

**Issue by ManojkumarMuralidharan** [RafalWilinski/express-status-monitor#73]
The current version of the module is 0.1.8. However the npm module which is published is 0.1.7. Can we add a step to automate publishing to npm, as soon as a PR is merged ? Also can we publish 0.1.8 to npm, asap ?

**Comment by RafalWilinski** [comment]
Fixed https://github.com/RafalWilinski/express-status-monitor/pull/84

**Comment by ManojkumarMuralidharan** [comment]
Awesome !!
