### ISSUE TITLE
Add TypeScript TypeDefinition

### ISSUE THREAD

**Issue by suleymanozev** [RafalWilinski/express-status-monitor#79]
Hi,
Could you add TypeScript Definition ?

**Comment by caseyWebb** [comment]
@RafalWilinski if you're not opposed to converting the project to TypeScript so that can be used to generate type definitions I'll take it on.

**Comment by RafalWilinski** [comment]
Sound like awesome idea! Would be great

**Comment by BCusack** [comment]
and for Deno url importing strategy

**Comment by sdc224** [comment]
Hi, is anyone working on the typescript definitions part? Or maybe converting this repo to typescript?
