### ISSUE TITLE
There is no way to change socket.io path

### ISSUE THREAD

**Issue by serkanyersen** [RafalWilinski/express-status-monitor#83]
my application lives under a subfolder of a different app, e.g `example.com/my-app/`

I've configured status monitor to run under a different path like so `example.com/my-app/_status/`

however, when it runs, it tries to get the socket.io from the root, `example.com/socket.io/` and unfortunately that won't work.

I need a way to configure socket.io so that it can run under `example.com/my-app/socket.io/`

it would be even better if I can authenticate that socket using the same authentication I use on the status page. people can bypass the authentication I put by simply plugging into that socket I assume.

Here is what my code looks like.
```javascript
const config = require('./config');
const expressStatusMonitor = require('express-status-monitor');
const auth = require('http-auth');

const statusMonitor = expressStatusMonitor({
  title: 'My App | Server Status',
  path: '_status',
});
const basic = auth.basic({ realm: 'Monitor Area' }, (user, pass, callback) => {
  callback(user === config.credentials.status.username
        && pass === config.credentials.status.password);
});

module.exports = function setupStatusMonitor (app) {
  app.use(statusMonitor.middleware);
  app.get('/my-app/_status/logout', (req, res) => res.send(401, 'logged-out'));
  app.get('/my-app/_status', auth.connect(basic), statusMonitor.pageRoute);
};
```

**Comment by lxinspc** [comment]
if it's still of use, I've hacked together a quick solution for this…

**Comment by RafalWilinski** [comment]
Please share it with us!
