### ISSUE TITLE
support different ports on html and nodejs, or listen(server)

### ISSUE THREAD

**Issue by txchen** [RafalWilinski/express-status-monitor#9]
Nice project, thanks for making this!

I found that this does not work for my setup. I have an ngnix sits in front of my nodejs app, and  SSL terminates on nginx.

Suppose my site is https://www.a.com

The html will let the js try to connect https://www.a.com:41388, this will not work because nodejs level does not support ssl. I cannot make nginx listen on 41388, because nodejs already took that.

To solve the issue, I think there are 2 options:

1) extend the config, add one more public port. so js will use this port to connect, it will reach nginx, then redirects to nodejs port. This requires nginx and nodejs listen on two different ports. Now the config does not support that.
2) let socket.io listen on the same port with express, I think it is doable, by listen(server)

I prefer 2), it is cleaner and use one less port.

Please let me know what do you think, thanks a lot!

**Comment by txchen** [comment]
This is related to #7 actually.

**Comment by RafalWilinski** [comment]
Fixed here: https://github.com/RafalWilinski/express-status-monitor/commit/d6327597a75b08ca923ce9ff444ca0647842285a

Now Socket.io uses same port as Express server which gives us also https support.
Thanks!
