### ISSUE TITLE
Monitor or exclude specific endpoints

### ISSUE THREAD

**Issue by loretoparisi** [RafalWilinski/express-status-monitor#94]
My application has different endpoints in term of app logic (like admin and rest data endpoint), and I would like to monitor certain endpoints under some routes like `['/api']` and exclude others like `['/admin']`. How to add this logic?

**Comment by RafalWilinski** [comment]
Added `ignoreStartsWith` config option here: https://github.com/RafalWilinski/express-status-monitor/commit/571542d8d6544de200273a48e0bbd7a5614a0136

For example, if you specify `ignoreStartsWith: /api` then all requests to e.g. `/api/user/1` or just `/api` will be ignored by ESM.
