### ISSUE TITLE
Release 1.1 not available via NPM

### ISSUE THREAD

**Issue by antonioaguilar** [RafalWilinski/express-status-monitor#98]
I wanted to try the `hide chats` feature but it seems it's only available on 1.1. In 1.0.1 the property `chartVisibility` seems to be ignored. Could you please release 1.1. to npm so I could do some testing. 

```
 chartVisibility: {
    cpu: true,
    mem: true,
    load: true,
    responseTime: false,
    rps: false,
    statusCodes: false
  }
```

thanks.

**Comment by antonioaguilar** [comment]
@RafalWilinski could you please "npm" publish the latest branch / release of this library. It would be nice try out the latest features. Thanks.

**Comment by RafalWilinski** [comment]
published.
